[package]
name = "anyroot"
version = "0.1.0"
edition = "2021"

[dependencies]
root-io = { path = "../alice-rs/root-io" }
tokio = { version = "1.43.0", features = ["rt", "macros"] }

[dev-dependencies]
root-ls = "0.2.0"
